### PR TITLE
Template views

### PR DESCRIPTION
**Pull request by mtfuller**
This branch includes styled views for Member and Events. Please look over it and let me know if there is anything I left out. Anything from `karim_member_view` branch?

### CODE REVIEW

**Comment by karimrattani** [comment]
For events: Do we need to display all the events or the future events only?
For members view: Isn't point only for officer? We can show user specific points in profile setting probably but I don't think it should show everybody's point.

I did both of those in karim_member_view branch. If we don't need above suggestions then branch looks good to get merge

**Comment by mtfuller** [comment]
@karimrattani Both are good calls. I'll look at your code and see if I can borrow the logic.

**Comment by mtfuller** [comment]
@karimrattani How about now? Care to take a look? Any other items we should add/modify?

**Comment by karimrattani** [comment]
i think it looks good for now, it will be easy to modify view later now since we have all the things we need. If everyone else is ok with it, we can merge it up

**Pull request merged**
